In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np
import project
import scale

From page 435 in the Bertsikas textbook there is an algorithm that we are testing here 

Steps:

*Remember overall we are looking for directions, and step lengths.  We do the same for the primal path following method*


- Choose initial feasible points for $x_0$, $s_0$, and $p_0$
- Choose direction that is primal and dual feasible
    - Remember that in this case we have the non-linearity from the KKT conditions, so we can't just solve using a linear system (i.e. a projection)
- Use Newton's method to find those directions
- Update $x_0$, $s_0$, and $p_0$

In [204]:
# inputs to the solver:

A = np.matrix([[1,2,0,0],
              [0,1,0,0],
              [0,0,1,1],
              [0,0,0,1]])
b = np.asmatrix(np.array([0.0,0.0, 0.5, 0.1])).reshape(4,1)
c = np.asmatrix(np.array([0.1,0.0, 1.0, 1.5])).reshape(4,1)

In [205]:
# hyperparameters 
alpha = 0.01
epsilon = 10**-3

In [207]:
# starting conditions

x_0 = np.asmatrix(np.ones(shape=(4,1)))
p_0 = np.asmatrix(np.ones(shape=(4,1)))
s_0 = np.asmatrix(np.ones(shape=(4,1)))

In [220]:
X_k = np.diag(np.asarray(x_k).flatten())
S_k = np.diag(np.asarray(s_k).flatten())

In [221]:
s_k.T*x_k

matrix([[ 4.]])

In [209]:
x_k = x_0
s_k = s_0
p_k = p_0
epsilon = 10**1

# check if our duality gap is close to zero
# s_k.T*x_k is a proxy for mu, which means we are actually checking if the duality gap is close to zero.

k = 0
while (s_k.T*x_k) > epsilon:
    print 'starting the ', k, 'th iteration'
    # reformulate the arrays into matrix form
    # X_k and S_k should always be invertible since they are diagonal, EXCEPT if you started from a zero vector
    X_k = np.diag(np.asarray(x_k).flatten())
    S_k = np.diag(np.asarray(s_k).flatten())
    u_k = 3
    
    # solve the linear equations that were a result of Newtons method
    # (outputs of this part should be dx, dy, ds)
    dx, dy, ds = get_newton_directions(A, S_k, X_k, mu)
    
    # solve next system to get how FAR we should move in each direction
    B_P_k = min(1, alpha*)
    B_D_k = min(1, alpha*)
    
    # use directions and magnitudes to update x, s, and p
    
    # we could check feasibility for fun (or at least check that x, s, and p are all positive)
    
    k +=1


In [222]:
# 
X_k*np.linalg.pinv(S_k)
# 

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [237]:
P_k = D_k*A.T*np.linalg.inv(A*D_k_2*A.T)*A*D_k

In [235]:
D_k_2

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [236]:
D_k = np.sqrt(D_k_2)

In [229]:
D_k_2 = X_k*np.linalg.inv(S_k)

In [230]:
v_k_mu_k = np.linalg.inv(X)*D_k*(mu*np.asmatrix(np.ones(shape=(S.shape[0],1))) - X*S*np.asmatrix(np.ones(shape=(S.shape[0],1))))

In [231]:
v_k_mu_k

matrix([[-0.9],
        [-0.9],
        [-0.9]])

In [232]:
def get_newton_directions(A, S, X, mu):
    # as a sanity check, maybe try solving the linear system a few different ways and see if you get the same answer always
    D_k_2 = X*np.linalg.pinv(S)  # since S and X are diagonal matrices, they should usually be invertible as long as not zero
    D_k = np.sqrt(D_k_2)
    P_k = D_k*A.T*np.linalg.inv(A*D_k_2*A.T)*A*D_k   # would be best to do symbollically, since we are taking powers and square roots
    v_k_mu_k = np.linalg.inv(X)*D_k*(mu*np.asmatrix(np.ones(shape=(S.shape[0],1))) - X*S*np.asmatrix(np.ones(shape=(S.shape[0],1))))
    
    d_x_k = D_k*(np.asmatrix(np.eye(S.shape[0])))
    d_p_k = -np.linalg.inv(A*D_k_2*A.T)*A*D_k*v_k_mu_k
    d_s_k = np.linalg.inv(D_k)*P_k*v_k_mu_k
    
    return d_x_k, d_p_k, d_s_k
    

In [35]:
def Newtons_method(F, z_prime):
    '''
    Find the roots of F, which is a function of z
    z_prime is your initial guess
    z_prime is a vector of [x, p, s]

    Args:
        F (original functions as an array of functions as a sympy object) (e.g. F=sympy.Matrix([[f1], [f2]]))
    Returns:
        The locations of the roots of F, in vector form.
    '''
    # the Jacobian should be a matrix
    
        

In [36]:
# import sympy
# import numpy as np
# x,y = sympy.symbols('x,y', real=True)
# J = sympy.Function('F')(x,y)

Should we do Newtons method numerically or symbolically?  Symbolically, or at least let's try

In [12]:
from mpmath import *
mp.dps = 30; 
mp.pretty = True
findroot(lambda x: x**3 + 2*sin(0.34*x) + 1, 1.4)

-0.780500864018466543530607672654

In [ ]:
findroot(sin, initial_guess)

In [3]:
import scipy

Try to use sympy to evaluate the first derivative

In [34]:
import sympy
import numpy as np
x,y = sympy.symbols('x,y', real=True)
J = sympy.Function('J')(x,y)

In [28]:
f1=-y
f2=x - 3*y*(1-x**2)
f1x=sympy.diff(f1,x)
f1y=sympy.diff(f1,y)
f2x=sympy.diff(f2,x)
f2y=sympy.diff(f2,y)
# need to use sympy tools for this - not numpy
# cannot assign sympy.Matrix to "J", since "J" is a function
J = sympy.Matrix([[f1x,f1y],[f2x, f2y]])
J1 = J.subs([(0,0),(0,0)])
print J1

J2 = J.subs(10,-230)
print J2

Matrix([[0, -1], [6*x*y + 1, 3*x**2 - 3]])
Matrix([[0, -1], [6*x*y + 1, 3*x**2 - 3]])


In [33]:
F.jacobian([x,y])

AttributeError: 'J' object has no attribute 'jacobian'

In [22]:
print J

Matrix([[0, -1], [6*x*y + 1, 3*x**2 - 3]])


In [23]:
# evaluate J at certain point

In [24]:
sympy.pprint(F.jacobian([x,y]).subs([(x,0),(y,0)]))

AttributeError: 'J' object has no attribute 'jacobian'