In [1]:
import numpy as np
import project
import scale

In [2]:
def generate_A(n):
    A = -100*np.random.rand(n,n) #+np.eye(n)*800
    return A

In [3]:
mu = 0.5
e = np.array([1,1])
A = np.matrix([[1,1],
              [1,0]])
x = np.array([1,2])

In [4]:
dx, ds = project.project(A,mu)

In [5]:
proj_A = np.matrix([[ 1.,  0.], [ 0.,  1.]])

In [6]:
np.linalg.eig(proj_A)[0]

array([ 1.,  1.])

In [7]:
proj_A = A*np.linalg.inv(A.T*A)*A.T
check_eigs = np.vectorize(lambda x: float(x) == 1.0 or x == 0.0)
proj_A_eigs = np.linalg.eig(proj_A)[0]

In [8]:
np.alltrue(check_eigs(proj_A_eigs))

True

In [9]:
dx

matrix([[ 0.5],
        [ 0.5]])

In [10]:
ds

matrix([[  5.55111512e-17],
        [  0.00000000e+00]])

### make A a bit more complicated

In [11]:
mu = 700
n = 3
A = generate_A(n)

In [12]:
dx, ds = project.project(A,mu)

In [13]:
A

array([[-88.69575719, -75.16295754, -65.20623309],
       [-58.27232269, -94.52956621, -93.01198303],
       [-42.57679619, -92.71773928, -91.56979591]])

In [14]:
dx

matrix([[ 700.],
        [ 700.],
        [ 700.]])

In [15]:
ds

matrix([[  1.13686838e-13],
        [  1.13686838e-13],
        [  0.00000000e+00]])

In [16]:
mu*dx + ds

matrix([[ 490000.],
        [ 490000.],
        [ 490000.]])

In [17]:
# let's see if these check out:

mu*dx + ds == mu*e

matrix([[False, False],
        [False, False],
        [False, False]], dtype=bool)

In [18]:
A*dx 

matrix([[-160345.46346968],
        [-172069.71035978],
        [-158805.0319629 ]])

#### QR decomposition gives basis vectors of A

In [19]:
q,r = np.linalg.qr(A)

In [20]:
q

array([[-0.77566753,  0.59527023,  0.20974566],
       [-0.50960666, -0.39464741, -0.76456162],
       [-0.37234519, -0.69993341,  0.60946885]])

In [21]:
q_inv = np.linalg.inv(q)

In [22]:
q_inv

array([[-0.77566753, -0.50960666, -0.37234519],
       [ 0.59527023, -0.39464741, -0.69993341],
       [ 0.20974566, -0.76456162,  0.60946885]])

In [23]:
r

array([[ 114.34764759,  140.99736589,  132.07345636],
       [   0.        ,   57.45982129,   61.98436871],
       [   0.        ,    0.        ,    1.62772965]])

In [24]:
r_inv = np.linalg.inv(r)

In [25]:
r_inv

array([[ 0.00874526, -0.02145949,  0.10759552],
       [ 0.        ,  0.01740347, -0.66272848],
       [ 0.        ,  0.        ,  0.61435263]])

##### first "n" columns of the matrix Q form a basis for A.  n = rank(A)

In [26]:
n = np.linalg.matrix_rank(A)
Q, R = np.linalg.qr(A)

In [27]:
np.asmatrix(Q)

matrix([[-0.77566753,  0.59527023,  0.20974566],
        [-0.50960666, -0.39464741, -0.76456162],
        [-0.37234519, -0.69993341,  0.60946885]])

get first n columns

In [28]:
np.asmatrix(Q)[:,0:n]

matrix([[-0.77566753,  0.59527023,  0.20974566],
        [-0.50960666, -0.39464741, -0.76456162],
        [-0.37234519, -0.69993341,  0.60946885]])

For the stackoverflow question, here's how we solved the system using a projection:
1) 