In [1]:
import numpy as np
import project
import scale

In [33]:
def generate_A(n):
    A = np.random.rand(n,n)+np.eye(n)
    return A

In [34]:
mu = 0.5
e = np.array([1,1])
A = np.matrix([[1,1],
              [1,0]])
x = np.array([1,2])

In [35]:
dx, ds = project.project(A,mu)

In [36]:
dx

matrix([[ 0.5],
        [ 0.5]])

In [37]:
ds

matrix([[ 0.],
        [ 0.]])

### make A a bit more complicated

In [42]:
mu = 700
n = 10
A = generate_A(n)

In [43]:
dx, ds = project.project(A,mu)

In [44]:
dx

matrix([[ 700.],
        [ 700.],
        [ 700.],
        [ 700.],
        [ 700.],
        [ 700.],
        [ 700.],
        [ 700.],
        [ 700.],
        [ 700.]])

In [45]:
ds

matrix([[  0.00000000e+00],
        [  1.13686838e-13],
        [  0.00000000e+00],
        [  1.13686838e-13],
        [  0.00000000e+00],
        [  1.13686838e-13],
        [ -1.13686838e-13],
        [  1.13686838e-13],
        [  1.13686838e-13],
        [  0.00000000e+00]])