In [1]:
import numpy as np
import project
import scale

In [2]:
def generate_A(n):
    A = -100*np.random.rand(n,n) #+np.eye(n)*800
    return A

In [3]:
mu = 0.5
e = np.array([1,1])
A = np.matrix([[1,1],
              [1,0]])
x = np.array([1,2])

In [4]:
dx, ds = project.project(A,mu)

the basis vectors for the columnspace of A are  [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [5]:
dx

matrix([[ 1.],
        [ 1.]])

In [6]:
ds

matrix([[  1.11022302e-16],
        [  0.00000000e+00]])

### make A a bit more complicated

In [28]:
mu = 700
n = 3
A = generate_A(n)

In [29]:
dx, ds = project.project(A,mu)

the basis vectors for the columnspace of A are  [[-0.6209737  -0.27361139 -0.73452602]
 [-0.37356846 -0.72051695  0.58421053]
 [-0.6890851   0.63717512  0.34520949]]


In [35]:
A

array([[-85.29399096, -49.10777135, -31.80632877],
       [-51.31158496, -48.27072337, -82.18929242],
       [-94.64944874, -22.79969524,  -3.8743676 ]])

In [36]:
dx

matrix([[ 1.],
        [ 1.],
        [ 1.]])

In [32]:
ds

matrix([[ -2.22044605e-16],
        [  0.00000000e+00],
        [ -2.22044605e-16]])

In [34]:
mu*dx + ds

matrix([[ 1.],
        [ 1.],
        [ 1.]])

In [12]:
# let's see if these check out:

mu*dx + ds == mu*e

matrix([[ True,  True],
        [ True,  True],
        [False, False]], dtype=bool)

In [24]:
A*dx 

matrix([[ -92.83687325],
        [-110.83461339],
        [-134.74635981]])

#### QR decomposition gives basis vectors of A

In [14]:
q,r = np.linalg.qr(A)

In [15]:
q

array([[-0.46263725,  0.85678447, -0.22778752],
       [-0.69080057, -0.50942726, -0.51310666],
       [-0.55566299, -0.0800265 ,  0.82754722]])

In [16]:
q_inv = np.linalg.inv(q)

In [17]:
q_inv

array([[-0.46263725, -0.69080057, -0.55566299],
       [ 0.85678447, -0.50942726, -0.0800265 ],
       [-0.22778752, -0.51310666,  0.82754722]])

In [18]:
r

array([[ 84.25089759,  22.28326781,  87.8538086 ],
       [  0.        , -13.7403055 ,   1.44456808],
       [  0.        ,   0.        , -33.49191615]])

In [19]:
r_inv = np.linalg.inv(r)

In [20]:
r_inv

array([[ 0.01186931,  0.01924899,  0.03196504],
       [-0.        , -0.07277859, -0.00313907],
       [-0.        , -0.        , -0.02985795]])

##### first "n" columns of the matrix Q form a basis for A.  n = rank(A)

In [21]:
n = np.linalg.matrix_rank(A)
Q, R = np.linalg.qr(A)

In [22]:
np.asmatrix(Q)

matrix([[-0.46263725,  0.85678447, -0.22778752],
        [-0.69080057, -0.50942726, -0.51310666],
        [-0.55566299, -0.0800265 ,  0.82754722]])

get first n columns

In [23]:
np.asmatrix(Q)[:,0:n]

matrix([[-0.46263725,  0.85678447, -0.22778752],
        [-0.69080057, -0.50942726, -0.51310666],
        [-0.55566299, -0.0800265 ,  0.82754722]])